feat(python-jupyter): Setting up venv in a dedicated volume
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>

diff --git a/sidecars/python/Dockerfile b/sidecars/python/Dockerfile
--- a/sidecars/python/Dockerfile
+++ b/sidecars/python/Dockerfile
@@ -12,13 +12,6 @@ FROM python:3.8.6-slim
 
 ENV HOME=/home/theia
 
-RUN mkdir /projects ${HOME} && \
-    # Change permissions to let any arbitrary user
-    for f in "${HOME}" "/etc/passwd" "/projects"; do \
-      echo "Changing permissions on ${f}" && chgrp -R 0 ${f} && \
-      chmod -R g+rwX ${f}; \
-    done
-
 RUN apt-get update && \
     apt-get install exuberant-ctags && \
     apt-get install wget -y && \
@@ -28,6 +21,24 @@ RUN apt-get update && \
     pip install pylint python-language-server[all] ptvsd jedi && \
     apt-get purge -y --auto-remove gcc build-essential && \
     apt-get clean && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*
+
+
+SHELL ["/bin/bash", "-c"]
+RUN command -v source || (echo "ERROR: Could not find 'source' command. SHELL may not supported. If you are using podman, try again with the '--format docker' flag." && exit 126)
+
+RUN cd "${HOME}"; \
+    python -m venv .venv ; \
+    source .venv/bin/activate; \
+    pip install -U ipykernel jupyter; \
+    python -m ipykernel install --name=.venv --user; \
+    mv "${HOME}"/.venv "${HOME}"/.venv-tmp
+
+RUN mkdir /projects && \
+    # Change permissions to let any arbitrary user
+    for f in "${HOME}" "/etc/passwd" "/projects"; do \
+      echo "Changing permissions on ${f}" && chgrp -R 0 ${f} && \
+      chmod -R g+rwX ${f}; \
+    done
 
 ADD etc/entrypoint.sh /entrypoint.sh
 ENTRYPOINT [ "/entrypoint.sh" ]
