Fix release.yaml formatting

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,23 +28,23 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
-    - name: Check existing tags
-      run: |
-        set +e
-        RECREATE_TAGS=${{ github.event.inputs.forceRecreateTags }}
-        VERSION=${{ github.event.inputs.version }}
-        EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
-        if [[ -n ${EXISTING_TAG} ]]; then
-          if [[ ${RECREATE_TAGS} == "true" ]]; then
-            echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
-            git push origin :$VERSION
+      - name: Check existing tags
+        run: |
+          set +e
+          RECREATE_TAGS=${{ github.event.inputs.forceRecreateTags }}
+          VERSION=${{ github.event.inputs.version }}
+          EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
+          if [[ -n ${EXISTING_TAG} ]]; then
+            if [[ ${RECREATE_TAGS} == "true" ]]; then
+              echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
+              git push origin :$VERSION
+            else
+              echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
+              exit 1
+            fi
           else
-            echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
-            exit 1
+            echo "[INFO] No existing tags detected for $VERSION"
           fi
-        else
-          echo "[INFO] No existing tags detected for $VERSION"
-        fi
       - name: Login to Quay.io
         uses: azure/docker-login@v1
         with:
